// src/lib/components/WelcomeSection.svelte
<script>
  import ButtonLink from './ButtonLink.svelte';
  import RoundedImage from './RoundedImage.svelte';
  import massageImg from '$lib/assets/massage.webp';
  import oilsImg from '$lib/assets/oils.webp';
  import flower from '$lib/assets/flower.webp';
  import bachImg from '$lib/assets/bach.webp';
  import signatureImg from '$lib/assets/signature-soin.webp';
  import separator from '$lib/assets/separator.webp';
</script>

<section class="welcome-section" aria-label="Accueil">
  <img src={flower} class="flower1" alt="" aria-hidden="true" />
  <img src={flower} class="flower2" alt="" aria-hidden="true" />
  <h1>AROMANESSENCES</h1>
  <p class="tagline">
    Fournisseur de bien être : Conseillère en Huiles Essentielles, praticienne
    en Fleurs de Bach et praticienne en massage assis AMMA.
  </p>
  <img src={separator} class="separator" alt="" aria-hidden="true" />
  <p>
    Aromanessences vous permet une approche différente du bien être physique,
    psychique et émotionnel grâce aux huiles essentielles, hydrolats, huiles
    végétales, fleurs de bach et la pratique du massage assis dit AMMA. Qui
    peut se pratiquer en cabinet, à domicile, en entreprise, lors de
    manifestations .... Je vous accompagne dans un bien être total grâce au
    mariage de toutes ces pratiques.
  </p>
  <nav class="categories" aria-label="Catégories de services">
    <RoundedImage imgSrc={oilsImg} link="oils" alt="Flacons d'huiles essentielles" data-aos="fade-down">
      Huiles essentielles
    </RoundedImage>
    <RoundedImage imgSrc={bachImg} link="bach" alt="Fleurs de Bach" data-aos="fade-down">
      Fleurs de bach
    </RoundedImage>
    <RoundedImage imgSrc={massageImg} link="massage" alt="Massage assis sur chaise" data-aos="fade-down">
      Massage assis
    </RoundedImage>
    <RoundedImage imgSrc={signatureImg} link="signature-soin" alt="Soin des mains signature" data-aos="fade-down">
      Soin signature
    </RoundedImage>
  </nav>
</section>

<style lang="scss">
  .welcome-section {
    padding: 20px;
    background-color: $primary;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 25px 25% 170px 25%;
    position: relative;
  }

  h1 {
    font-size: 72px;
    margin: 0;
  }

  .tagline {
    font-size: 1.1em;
    font-weight: 400;
    margin: 1em 0;
  }

  .categories {
    position: absolute;
    width: 80%;
    background-color: white;
    top: 450px;
    gap: 70px;
    box-shadow: 0 15px 50px rgba(157, 168, 130, 0.15);
    border-radius: 20px;
    padding: 50px 30px 30px 30px;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .separator {
    width: 50px;
  }

  .flower1 {
    position: absolute;
    width: 100px;
    top: 0;
    right: 0;
  }

  .flower2 {
    position: absolute;
    width: 100px;
    top: 0;
    left: 0;
    transform: scaleX(-1);
  }

  @media screen and (max-width: $mobileBreakpoint) {
    h1 {
      font-size: 30px;
      margin-top: 25px;
    }

    .welcome-section {
      padding: 50px 15% 170px 15%;
    }

    .categories {
      top: 85%;
      padding: 30px;
      gap: 20px;
      flex-direction: column;
    }
  }
</style>

// front/src/components/WelcomeSection.vue
<template>
  <div class="welcome-section">
    <img :src="flower" class="flower1" />
    <img :src="flower" class="flower2" />
    <h1>AROMANESSENCES</h1>
    <h3>
      Fournisseur de bien être : Conseillère en Huiles Essentielles, praticienne
      en Fleurs de Bach et praticienne en massage assis AMMA.
    </h3>
    <img src="../assets/separator.png" class="separator" alt="separator" />
    <p>
      Aromanessences vous permet une approche différente du bien être physique,
      psychique et émotionnel grâce aux huiles essentielles, hydrolats, huiles
      végétales, fleurs de bach et la pratique du massage assis dit AMMA. Qui
      peut se pratiquer en cabinet, à domicile, en entreprise, lors de
      manifestations .... Je vous accompagne dans un bien être total grâce au
      mariage de toutes ces pratiques.
    </p>
    <CustomButton link="contact">Contact</CustomButton>
    <div class="categories">
      <RoundedImage
        :imgSrc="massageImg"
        link="massage"
        class="first-image"
        data-aos="fade-down"
      >
        Massage assis
      </RoundedImage>
      <RoundedImage
        :imgSrc="oilsImg"
        link="oils"
        class="first-image"
        data-aos="fade-down"
      >
        Huiles essentielles
      </RoundedImage>
      <RoundedImage :imgSrc="bachImg" link="bach" data-aos="fade-down">
        Fleurs de bach
      </RoundedImage>
    </div>
  </div>
</template>

<script>
import CustomButton from './CustomButton.vue';
import RoundedImage from './RoundedImage.vue';
import massageImg from '../assets/massage.jpg';
import oilsImg from '../assets/oils.jpg';
import flower from '../assets/flower.png';
import bachImg from '../assets/flower.jpg';

export default {
  name: 'WelcomeSection',
  components: { CustomButton, RoundedImage },
  data() {
    return {
      massageImg,
      oilsImg,
      flower,
      bachImg,
    };
  },
};
</script>

<style lang="scss" scoped>
.welcome-section {
  padding: 20px;
  background-color: $primary;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 50px 25% 170px 25%;
  position: relative;
}
h1 {
  font-size: 70px;
  margin: 0;
}
.categories {
  position: absolute;
  width: 70%;
  background-color: white;
  top: 450px;
  box-shadow: 1px 1px 24px 5px rgba(0, 0, 0, 0.1);
  padding: 50px 30px 30px 30px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.first-image {
  margin-right: 100px;
}
.separator {
  width: 50px;
}

.organic1 {
  position: absolute;
  top: 100px;
  left: -190px;
  width: 500px;
}

.organic2 {
  position: absolute;
  top: -50px;
  transform: rotate(90deg);
  right: -190px;
  width: 500px;
}
.flower1 {
  position: absolute;
  width: 100px;
  top: 0;
  right: 0;
}
.flower2 {
  position: absolute;
  width: 100px;
  top: 0;
  left: 0;
  transform: scaleX(-1);
}
@media screen and (max-width: $mobileBreakpoint) {
  h1 {
    font-size: 30px;
  }
  .welcome-section {
    padding: 50px 15% 170px 15%;
  }
  .categories {
    top: 85%;
    padding: 30px;
    flex-direction: column;
  }
  .first-image {
    margin: 0 0 20px 0;
  }
  .organic1,
  .organic2 {
    display: none;
  }
}
</style>
